---
configure_terminal: yes
configure_osx: yes
configure_dotfiles: yes

dotfiles_repo: https://github.com/danielonthenet/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .zshrc
  - .gitconfig
  - .osx
  - .functions

homebrew_installed_packages:
# Dev
  - git
  - go
  - httpie
  - jq
  - jmeter
  - maven
  - python
  - python3
  - sqlite  
# Shell Utilities 
  - coreutils
  - tree
  - csshx
  - fzf
  - knock
  - whatmask
  - wget
  - antigen #package manager for zsh
  - autojump
  - nmap
  - ssh-copy-id
  - openssl
  - pandoc
# Cloud
# DevOps
  - kubernetes-cli
  - kubernetes-helm
  - terraform

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
# Messaging and co.
  - slack
# Browsers
  - google-chrome
  - firefox
# Utilities
  - vlc
  - filezilla
  #- cyberduck
  - mas
  #- microsoft-office
  #- licecap
  #- handbrake
# DevOps tools
  - docker
  - vagrant
  - virtualbox
# Dev environment
  - java
  - node
  - sourcetree
  - postman
  - intellij-idea
  - visual-studio-code
# Databases
  - sequel-pro
  - postico
# Quick look plugins
  - qlcolorcode
  - qlstephen
  - qlmarkdown
  - quicklook-json
  - qlprettypatch
  - quicklook-csv
  - betterzipql
  - qlimagesize
  - webpquicklook
  - go2shell # Opens a terminal window to the current directory in Finder.

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 425955336 # Skitch
  - 472226235 # LanScan
  - 1295203466 # Microsoft Remote Desktop
  - 1362171212 # Caffeinated

#mas_email: ""
#mas_password: ""

vscode_packages:
  #- vscoss.vscode-ansible # Ansible 
  #- mrmlnc.vscode-apache # Apache config
  #- shanoor.vscode-nginx # NGinx config
  #- HookyQR.beautify # Beautify code
  #- CoenraadS.bracket-pair-colorizer-2 # Colorizing matching brackets
  #- eamodio.gitlens # Supercharge Git 
  #- fatihacet.gitlab-workflow # Gitlab workflow integration
  #- akamud.vscode-theme-onedark # Theme
  #- file-icons.file-icons #Icons
  #- bmaupin.copy-without-formatting # Copy without formatting
  #- caarlos0.language-prometheus # Syntax highlight and snippets for Prometheus'
  #- christian-kohler.npm-intellisense # Autocomplete npm
  #- christian-kohler.path-intellisense # Autocompletes filenames
  #- DotJoshJohnson.xml # ML formatting
  #- EditorConfig.EditorConfig # EditorConfig Support
  #- eg2.vscode-npm-script # npm support
  #- esbenp.prettier-vscode # Prettier 
  #- formulahendry.code-runner # Run code from vscode
  #- Gruntfuggly.todo-tree # Show Todo Fixme 
  #- johnpapa.angular-essentials # Essential extensions for Angular developers
  #- johnpapa.Angular2 # Angular
  #- mauve.terraform # Terraform
  #- Mikael.Angular-BeastCode # Angular
  #- mitchdenny.ecdc # Encode and decode text selections
  #- ms-azuretools.vscode-docker # Linting for Dockerfile and docker-compose files
  #- ms-kubernetes-tools.vscode-kubernetes-tools # Kubernetes
  #- ms-python.python # Python
  #- ms-vscode.azure-account # Azure
  #- ms-vscode.azurecli # Azure
  #- ms-vscode.Go # Go lang
  #- ms-vscode.vscode-typescript-tslint-plugin # TSLint support 
  #- ms-vsliveshare.vsliveshare # Real-time collaborative development
  #- msjsdiag.debugger-for-chrome # Debugger for Chrome
  #- mtxr.sqltools # Database management
  #- natewallace.angular2-inline
  #- nhoizey.gremlins # Reveals some characters that can be harmful because they are invisible or looking like legitimate ones
  #- quicktype.quicktype # Copy JSON, paste as Go, TypeScript, C#, C++ and more
  #- redhat.vscode-yaml # Yaml language support
  #- samuelcolvin.jinjahtml # Syntax highlighting for jinja
  #- spywhere.guides # Guide lines
  #- tht13.python # Python language
  #- vilicvane.sensitive-replace # Sensitive replace
  #- VisualStudioExptTeam.vscodeintellicode # AI-assisted development
  #- wayou.vscode-todo-highlight # highlight TODOs, FIXMEs, and any keywords, annotation
  #- yzane.markdown-pdf # Convert Markdown to PDF
