---
- name: Assure VScode and cli code command are installed.
  command: which code
  register: return_value
  check_mode: no
  failed_when: return_value.rc
  changed_when: False

- name: Ensure configured VScode packages are installed.
  command: "code --install-extension '{{ item }}'"
  with_items: "{{ vscode_packages }}"
  register: vscode_result
  changed_when: "'already installed' not in vscode_result.stdout"

- name: Settings VScode
  copy:
    src: settings.json
    dest: "~/Library/Application\ Support/Code/User/settings.json"
    mode: 0644
